swagger: "2.0"
info:
  title: "AZ OM-API"
  version: "0.0.1"
  description: "AZ OM API version 1.x"
basePath: "/az-api"
tags:
- name: "azapi"
  description: "az apit"
schemes:
- "http"
paths:
  /product/{productId}:
    get:
      tags:
      - "az"
      summary: "Returns all product of the given product-id."
      description: "Returns all product visible for the user matching filter criteria."
      operationId: "getProduct"
      produces:
      - "application/json"
      parameters:
        - name: "productId"
          in: "path"
          description: "Application id"
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Successful operation."
          schema:
            $ref: "#/definitions/Product"
        400:
          description: "Invalid parameter value."
        401:
          description: "Unauthorized - No user credentials where provided."
        403:
          description: "Forbidden - The user cannot access this resource."
        404:
          description: "Not Found - No result has been found matching the request criteria or the user lacks permissions to view this result."
          schema:
            $ref: "#/definitions/Error"
definitions:
  Product:
    description: The Response that may contain different variations of the telex to get displayed at the frontend
    type: object
    properties:
      name:
        type: string
        description: name
        example: "name"
      price:
        type: integer
        description: price
        example: "price"
      amount:
        type: integer
        description: amount
        example: "amount"
  Error:
    properties:
      error:
        type: string
        description: error
        example: "error"